item {
    name: "arrows_turn_left",
    id: 0,
    display_name: "arrows_turn_left"
}
item {
    name: "direction",
    id: 1,
    display_name: "direction"
}
item {
    name: "double_car",
    id: 2,
    display_name: "double_car"
}
item {
    name: "indication",
    id: 3,
    display_name: "indication"
}
item {
    name: "priority_lane",
    id: 4,
    display_name: "priority_lane"
}
item {
    name: "radar_area",
    id: 5,
    display_name: "radar_area"
}
item {
    name: "side_right",
    id: 6,
    display_name: "side_right"
}
item {
    name: "speed_110",
    id: 7,
    display_name: "speed_110"
}
item {
    name: "speed_30",
    id: 8,
    display_name: "speed_30"
}
item {
    name: "speed_50",
    id: 9,
    display_name: "speed_50"
}
item {
    name: "speed_70",
    id: 10,
    display_name: "speed_70"
}
item {
    name: "speed_90",
    id: 11,
    display_name: "speed_90"
}
item {
    name: "turn_right",
    id: 12,
    display_name: "turn_right"
}
